name: Standard pipeline to check module
on: [push]
permissions:
  contents: read
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false